### ISSUE TITLE
Language specific redirection page?

### ISSUE THREAD

**Issue by Ozkovacs** [techies23/Inactive-Logout#14]
Hi there.
Would it be possible to have a redirection page based on the language?
I have a bilingual WP site (EN and FR).  I have not issue having the popup message bilingual, but I'd like to have the EN folks redirected to the EN landing page, and the FR folks, to the FR landing page.

thanks!

**Comment by techies23** [comment]
Sorry, but for now i don't see a way to achieve this because there are alot of languages. I simply cannot add only FR and EN - this would be unfair. I'll see if i can do something on this. Please suggest if you have any ideas on how i would implement multi-language support here.
