### ISSUE TITLE
Set redirecton link for user group (In advance settings)

### ISSUE THREAD

**Issue by girisagar46** [techies23/Inactive-Logout#18]
Is there any way I can set Global page redirection for user group (say subscriber).

In this issue https://github.com/techies23/Inactive-Logout/issues/5, it is said that it is not supported for advance user. 

If I want to add that feature, what should I do to achieve this?

**Comment by techies23** [comment]
Hi there,

In current version of the plugin you can do that. It was just not possible in the older version. I have already added this in the latest version of the plugin. After you install goto settings > inactive logout and advanced management tab ( or role based management ).

From here you'll be able to global redirect via user group/user roles.

**Comment by girisagar46** [comment]
I just installed the latest one from GitHub release https://github.com/techies23/Inactive-Logout/releases/tag/1.9.0

How do I set up the global redirection link? I want users to go to a particular link after auto logout. I can only see "Set Global Redirection Page" 

![image](https://user-images.githubusercontent.com/6840782/58617423-07c0f880-82fb-11e9-8705-0caa569c8972.png)

**Comment by techies23** [comment]
For user roles i haven't added the external link yet - Maybe in the coming days - Sadly, only page redirection is available for now.

**Comment by girisagar46** [comment]
Oh. Okay. 
That would be a nice feature to have since in the Basic Management, we do have a redirect link. I don't know anything about PHP and Wordpress plugin, or else I would have tweak the plugin to get this working. 

Anyway thank you again. 😄
