### ISSUE TITLE
Activation Error

### ISSUE THREAD

**Issue by gr8wan** [techies23/Inactive-Logout#2]
Plugin could not be activated because it triggered a fatal error.

**Fatal error: Class 'Inactive__ConcurrentLogins_functions' not found in /home/gr8wan0090/public_html/wp-content/plugins/inactive-logout/src/inactive-logout-main.php on line 69**

**Comment by techies23** [comment]
Noticed !

Isset variable error... Fixing asap.

**Comment by gr8wan** [comment]
Outstanding! Thanks

**Comment by techies23** [comment]
Thank you for pointing out the error.. Error has been fixed please check and reply before closing..  :)

**Comment by gr8wan** [comment]
Works like a charm now. Superb job on this plugin btw.

Cheers!
