### ISSUE TITLE
Custom Redirect URL

### ISSUE THREAD

**Issue by gr8wan** [techies23/Inactive-Logout#5]
Back in February, I suggested the idea of redirecting to a specific (user defined) URL instead of existing pages or posts. I still think this would be a very useful feature as I have several medical and banking clients who would simply want to redirect their patients/clients to a specific page. I hope this is included in the next update since you are already halfway there with the ability to redirect to pages/posts.

**Comment by techies23** [comment]
k.. will work on it.. thnx

**Comment by techies23** [comment]
Added in 1.5.0 .. but cannot be activated in advanced management user role settings for now..
