### ISSUE TITLE
Feature request: session expire on sign up

### ISSUE THREAD

**Issue by alexlii1971** [techies23/Inactive-Logout#9]
Hello, 

I do not know whether the session will be automatically expire by default if user signout. if no, is it  possible to automatically make session or cookie expire on sigin up.

I mean, mostly, the users just close the brower but not click signout or quick button.
Thanks.

Alex

**Comment by techies23** [comment]
Currently it does not log out users if browser is closed without logout.

I had added this back but caused lots of problems so initially removed it. Need to debug it properly but will not be adding this feature at the moment ( need alot of testing).

**Comment by michaelrimbach** [comment]
We also need this functionality.
